Fill in some more deserializer code
This currently fails:

    npx tsc ./deserialize-1.ts ; and node ./deserialize-1.js
    deserialize-1.ts:75:9 - error TS2322: Type '(Path | AccessControlled<Definition<ta, va>>)[][]' is not assignable to type '[Path, AccessControlled<Definition<ta, va>>][]'.
      Type '(Path | AccessControlled<Definition<ta, va>>)[]' is not assignable to type '[Path, AccessControlled<Definition<ta, va>>]'.
        Target requires 2 element(s) but source may have fewer.

    75         Modules: input['modules'].map(decodeArrayElement)
               ~~~~~~~

      ../sample-output-morphir-ir/morphir/ir/Package.ts:15:5
        15     Modules: Array<[Morphir_IR_Module.ModuleName, Morphir_IR_AccessControlled.AccessControlled<Morphir_IR_Module.Definition<ta, va>>]>;
               ~~~~~~~
        The expected type comes from property 'Modules' which is declared here on type 'Definition<ta, va>'

    Found 1 error.